export {default as Home} from "./Home";
export {default as Men} from "./Men";
export {default as Women} from "./Women";
export {default as Kid} from "./Kid";
export {default as Sale} from "./Sale";
export {default as Trending} from "./Trending";
export {default as ErrorPage} from "./ErrorPage";
export {default as Cart} from "./Cart";
export {default as Payment} from "./Payment";
export{default as Login} from "./Login";
export{default as Register} from "./Register";
export{default as Wishlist} from "./Wishlist";